### ISSUE TITLE
Change Locale link does not give the option to insert the translation for the field.

### ISSUE THREAD

**Issue by redjanym** [sonata-project/SonataTranslationBundle#77]
Hello, i'm having this issue with v1.0.1. Followed all the installation instructions and now i have the Change Locale links(flags) in the Edit View but clicking them does not give me the empty input for translating the field that is declared as @Gedmo\Translatable in the Entity and in Update saves the record in the default language. Here is my code:
- config.yml
sonata_translation:
```yml
    locales: [en, it]
    default_locale: %locale%
    # here enable the types you need
    gedmo:
        enabled: true
```
- Entity
```php
/**
 * CompanyType
 * @ORM\Table(name="company_type")
 * @ORM\Entity(repositoryClass="CompanyTypeRepository")
 * @Gedmo\TranslationEntity(class="AppBundle\Entity\CompanyType\Translation")
 */
class CompanyType extends AbstractPersonalTranslatable implements TranslatableInterface
{
  .......
   /**
     * @var string
     * @Gedmo\Translatable()
     * @ORM\Column(name="name", type="string", length=255)
     * @Groups({"tree", "list", "details", "details_api"})
     */
    private $name;
   
  /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\CompanyType\Translation", mappedBy="object", orphanRemoval=true)
     */
    protected $translations;

/**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
    }

}
```
- Translation Entity
```php
namespace AppBundle\Entity\CompanyType;

use Doctrine\ORM\Mapping as ORM;
use Sonata\TranslationBundle\Model\Gedmo\AbstractPersonalTranslation;


/**
 * @ORM\Entity
 * @ORM\Table(
 *     name="company_type_translation",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="lookup_company_type_translation_idx", columns={
 *         "locale", "object_id", "field"
 *     })}
 * )
 */
class Translation extends AbstractPersonalTranslation
{
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\CompanyType", inversedBy="translations")
     * @ORM\JoinColumn(name="object_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $object;
}

```

Passing to v1.0.0 gives me incompatibility with SonataBlockBundle. 
Can anybody tell me whats the problem?
Thanks.

**Comment by amoussard** [comment]
Same problem here :(

**Comment by redjanym** [comment]
@amoussard can you show me your versions of SonataAdmin, SonataCore and SonataBlock Bundle?

**Comment by amoussard** [comment]
I took master version of each when installing yesterday. All up to date.

**Comment by redjanym** [comment]
Hello @rande can you help us here? According to @rande (https://gist.github.com/rande/9c0cfbd751d3e64b893f) all the Bundles of the SonataProject must be in their Stable Version. Which i have, but the problem seems to be in SonataAdmin Bundle which is in v2.4 and looks like TranslationBundle works only with <= v2.3. What do you think @amoussard ?

**Comment by dbu** [comment]
we fixed a couple of issues and i just tagged 1.0.2 - can you try with that version again?

**Comment by redjanym** [comment]
I just upgraded and the problem still exists. I must add something else. I found that the problem was with the **GedmoTranslatableListener** which was not callable by SonataTranslationBundle, so i call it with another custom listener. After achieving the translation i could not search for the translated values through the SonataAdmin Filter. Do you think this behaviour is also caused by the same issue as before?

**Comment by dbu** [comment]
i don't know what the exact issue is, and unfortunately am not familiar with gedmo. i only merged a bunch of fixes to avoid errors that did come up, and improve the PHPCR support, and hoped the issue you encountered would happen to be fixed as well.

why is the translatable listener not callable? is it not injected? or does it get confused with something else? if you can do a PR to fix things, that would be best as i have no setup to test the gedmo integration.

**Comment by redjanym** [comment]
I switched to a2lix/TranslationFormBundle, problem resolved.

**Comment by dbu** [comment]
thanks for the update
